server:
  applicationConnectors:
    - type: http
      port: 9185

  adminConnectors:
    - type: http
      port: 9186

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        layout:
          type: access-json
          timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
          prettyPrint: ${PRETTY_PRINT:-false}
          includes: [${LOGGING_TAGS:-timestamp, statusCode, requestUri, requestTime}]
          additionalFields:
            system: ${system}
            containerName: ${container}
            version: ${versionNumber}

#JSON logging settings
logging:
  #   The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ${LOGGING_LEVEL:-INFO}
  appenders:
    - type: console
      threshold: ${LOGGING_LEVEL:-INFO}
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        prettyPrint: ${PRETTY_PRINT:-false}
        includes: [timestamp, threadName, level, loggerName, message, mdc, exception]
        customFieldNames:
          logger: "class"
          X-Correlation-Id: "correlationId"
          exception: "stacktrace"
        additionalFields:
          system: ${system}
          container: ${container}
          version: ${versionNumber}
        #          pid: ${pid}
        includesMdcKeys: [X-Correlation-Id]
        flattenMdc: true
#        exception:
#          layout:
#            type: json
#            exception:
#              rootFirst: true
#              depth: 30
#              evaluators: [org.apache]

sqsConfiguration:
  queueUrl: https://sqs.${AWS_REGION}.amazonaws.com/${AWS_ACCOUNT_ID}/${ENVIRONMENT}-email-queue-queue
  queueRecheckInterval: 2000
  endPoint: https://sqs.${AWS_REGION}.amazonaws.com
  sqsProxy:
    host: ${SQUID_HOST}
    port: 3128

commonNotificationsConfig:
  port: 9200
  scheme: http
  host: dvla-common-notifications.notification-${NOTIFICATIONS_ENVIRONMENT}.svc.cluster.local
  timeoutSeconds: 120
  resourceHeader: dvla:uk.gov.dvla.osl.email.service
  originResourceHeader: dvla:RAVE-WEB

emailConfiguration:
    regionName: ${AWS_REGION}
    connectionTimeout: 2000
    connectionMaxIdleMillis: 60000
    requestTimeout: 120000
    proxy:
      host: ${SQUID_HOST}
      port: 3128
    templatePath: templates/
    emailClient: ${EMAIL_CLIENT:-log}


encryptionKey: ${ENCRYPTION_KEY}

## Generates the swagger API docs from the code annotations
swagger:
  resourcePackage: uk.gov.dvla.osl.dropwizard.bundles.status
  title: Email Service
  version: ${versionNumber}
  schemes:
    - https
